name: Deploy Website
on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint the code
        run: npm run lint
      - name: Test the code
        run: npm run test
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build the code
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
            # dist
            # package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Check the dist-files
        run: ls -al 
      - name: Check some server details
        run: |
          pwd
          whoami
          hostname
      - name: Deploy
        run: echo "Deploying..."
      # - name: Build 
      #   run: npm run build
      # - name: deploy
      #   run: echo "Deployment"      - name: Get Code