name: Events Demo 
on: 
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Output event data
         run: echo "${{ toJSON(github.event)}}"
       - name: Get the code
         uses: actions/checkout@v3
       - name: Install dependencies
         run: npm ci
       - name: Lint the code
         run: npm run lint
       - name: Test the code
         run: npm run build
       - name: Build 
         run: npm run build
       - name: deploy
         run: echo "Deployment"