name: Lint Test deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Lint the code
        run: npm run lint
      - name: Test the code
        run: npm run build
      - name: Build 
        run: npm run build
      - name: deploy
        run: echo "Deployment"
      
        

      #   - name: Get the code
      #   uses: actions/checkout@v3
      # - name: Install NodeJS
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'
      # - name: Install dependencies
      #   run: npm ci
      # - name: Run test
      #   run: npm test
      